name: Docker-install

on:
  push:
    branches:
      - pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Display
        run: echo "Welcome, Build docker image et verify if exist"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verification Doker
        run: sudo docker --version 

      - name: Docker compose
        run: sudo docker compose version
      
      - name: Enter dans app
        run: cd app && sudo docker build -t flaskapp:latest .
      
      - name: Installation by defautl in Ubuntu
        run: apt list --installed