name: FLASK CI

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r ./app/requirements.txt

    - name: Print debugging information
      run: |
        source venv/bin/activate
        echo "Python Version: $(python --version)"
        echo "Working Directory: $(pwd)"
        echo "Contents of Working Directory: $(ls -l)"
        echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

    - name: Deploy Your Application
      run: |
        source venv/bin/activate
        nohup python ./app/app.py &
        sleep 10 # Give the server some time to start

    - name: Run tests
      run: |
        source venv/bin/activate
        # Add your test commands here
        # For example, you might use curl to test your endpoints
        curl http://localhost:5000/books
