name: FLASK CI

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        pwd
        python -m pip install --upgrade pip
        python -m pip install -r ./app/requirements.txt

    - name: Print debugging information
      run: |
        echo "Python Version: $(python --version)"
        echo "Working Directory: $(pwd)"
        echo "Contents of Working Directory: $(ls -l)"
        echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

    - name: Deploy Your Application
      run: |
        # Add your deployment commands here
        # For example, you might use a script to deploy your Flask app
        pwd
        python ./app/flask.sh
