name: FLASK CI

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./app/requirements.txt

      - name: Start Flask server
        run: |
          python ./app/app.py &
          sleep 10 # Give the server some time to start
        env:
          FLASK_ENV: development # Optional, if you need to set environment variables

      - name: Run tests
        run: |
          # Make sure your tests are running against the Flask server
          curl http://localhost:5000/books
